### ISSUE TITLE
attention map visualization code

### ISSUE THREAD

**Issue by hello-bluedog** [Visual-AI/PruneVid#1]
Thanks for your wonderful work!!!
Could you release the attention score visualization code mentioned in paper?
I am very interested in the text-visual cross attention score in VLLMs.

**Comment by OliverHxh** [comment]
Thanks for reaching out.

Here I provide the core code for implementing the visualization of the attention map. I hope this would be helpful for you.
```
def text_attention_visualize(attentions, video, t, h, w, original_h, original_w):
    # attentions: layer_num, head_num, text_len, img_len
    # video: h (t*w) 3
    layer_num, head_num, _, _ = attentions.shape
    attentions = attentions.max(dim=1)[0]
    attentions = attentions.max(dim=1)[0]
    layer_num, num_img = attentions.shape
    attentions = attentions.view(layer_num, t, h*w)
    attentions = (attentions - attentions.min(dim=-1, keepdim=True)[0]) / (attentions.max(dim=-1, keepdim=True)[0] - attentions.min(dim=-1, keepdim=True)[0])
    attentions = attentions.view(layer_num, t, h, w)
    attentions = torch.nn.functional.interpolate(attentions, size=(original_h, original_w), mode='bilinear', align_corners=False)
    layer_imgs = []
    for i in range(layer_num):
        attention = attentions[i]  # t h w
        attention = attention.permute(1, 0, 2).contiguous().view(original_h, t*original_w)

        # 将注意力图转换为彩色heatmap
        attention_img = cv2.applyColorMap(np.uint8(255 * attention.cpu().numpy()), cv2.COLORMAP_JET)
        video = video.astype(np.uint8)
        overlayed_img = cv2.addWeighted(video, 0.6, attention_img, 0.4, 0)  # 调整这里的权重以改变叠加效果

        # 保存合并后的图像
        # cv2.imwrite(file_name+'_text_{}.jpg'.format(i), overlayed_img)
        layer_imgs.append(overlayed_img)

    return np.concatenate(layer_imgs, axis=0)
    ```

**Comment by qq1332427275** [comment]
Hello author, may I ask how to obtain the attention and other related parameters in your above code? Is there any implementation in your code? I also want to get a visualization of attention, thank you very much~

**Comment by hello-bluedog** [comment]
You can pass 'True' to 'output_attentions'  parameter when run 'model.generate' to get attention maps in every layers

**Comment by qq1332427275** [comment]
Thank you for your answer. I have received the attention map, but how can I output the attention heatmap on the input image now?

**Comment by qq1332427275** [comment]
@OliverHxh @hello-bluedog Hello author, I have tried to visualize the attention heatmap of each frame on llava-onevision, but I can't get the style in the paper. The different frames I generated have different attention positions in the same layer, which is very strange. Can you provide a code that can be run directly?
Thank you very much and look forward to your reply! Wish you all the best!
